**Importing libraries**

In [1]:
import pandas as pd
import json
from pandas import json_normalize

**Section1: CSV File**

In [10]:
datacsv = pd.read_csv("people.csv")
datacsv.head()

   id      name  age       city
0   1  Person_1   21      Paris
1   2  Person_2   22       Lyon
2   3  Person_3   23  Marseille
3   4  Person_4   24   Toulouse
4   5  Person_5   25     Nantes

In [12]:
print(datacsv.head())
print(datacsv.info())

   id      name  age       city
0   1  Person_1   21      Paris
1   2  Person_2   22       Lyon
2   3  Person_3   23  Marseille
3   4  Person_4   24   Toulouse
4   5  Person_5   25     Nantes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50 non-null     int64
 1   name    50 non-null     object
 2   age     50 non-null     int64
 3   city    50 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.7+ KB
None

**Section2: Excel file**

In [20]:
dataexcel = pd.read_excel("clients.xlsx")
print(dataexcel.head())
print(dataexcel.info())

   client_id    company   country  revenue
0       1001  Company_1    France    51500
1       1002  Company_2   Germany    53000
2       1003  Company_3     Spain    54500
3       1004  Company_4     Italy    56000
4       1005  Company_5  Portugal    57500
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  50 non-null     int64
 1   company    50 non-null     object
 2   country    50 non-null     object
 3   revenue    50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB
None

**Section3: JSON file**

In [24]:
with open("person.json") as f :
  datajson = json.load(f)
  ndata = json_normalize(datajson)
print(ndata.head())
print(ndata.info())

                                              people
0  [{'name': 'Person_1', 'age': 19, 'skills': ['S...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   people  1 non-null      object
dtypes: object(1)
memory usage: 140.0+ bytes
None

In [29]:
ndata.describe()

                                                   people
count                                                   1
unique                                                  1
top     [{'name': 'Person_1', 'age': 19, 'skills': ['S...
freq                                                    1